service: serverless-graphql-api

package:
    exclude:
        - test/**

provider:
    logRetentionInDays: 7
    name: aws
    runtime: nodejs12.x
    versionFunctions: false
    cfLogs: true
    memorySize: 256
    environment: ${file(./env.yml):${opt:env, self:custom.stage}}
    stage: local
    region: eu-west-1

custom:
    region: ${opt:region, self:provider.region}
    stage: ${opt:stage, self:provider.stage}
    cors: true

plugins:
    - serverless-plugin-typescript
    - serverless-offline

functions:
    graphql:
        handler: src/index.handler
        events:
            - http:
                  path: graphql
                  method: post
                  cors: ${self:custom.cors}
                  integration: lambda-proxy
            - http:
                  path: graphql
                  method: get
                  cors: ${self:custom.cors}
                  integration: lambda-proxy
